In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
genres = pd.read_csv('../TopGenres.csv')
genres

   RANK             GENRES MOVIES      TOTAL GROSS AVERAGE GROSS MARKET SHARE
0     1          Adventure  1,102  $64,529,536,530   $58,556,748       27.14%
1     2             Action  1,098  $49,339,974,493   $44,936,224       20.75%
2     3              Drama  5,479  $35,586,177,269    $6,495,013       14.97%
3     4             Comedy  2,418  $33,687,992,318   $13,932,172       14.17%
4     5  Thriller/Suspense  1,186  $19,810,201,102   $16,703,374        8.33%
5     6             Horror    716  $13,430,378,699   $18,757,512        5.65%
6     7    Romantic Comedy    630  $10,480,124,374   $16,635,118        4.41%
7     8            Musical    201   $4,293,988,317   $21,363,126        1.81%
8     9        Documentary  2,415   $2,519,513,142    $1,043,277        1.06%
9    10       Black Comedy    213   $2,185,433,323   $10,260,250        0.92%

In [ ]:
g